### ISSUE TITLE
Support burn operations

### ISSUE THREAD

**Issue by JakeUrban** [Creit-Tech/xBull-Wallet#10]
This is definitely a niche action, but I wanted to burn my balance of an asset by sending it back to the issuer. xBull suggested that I use a claimable balance because the destination account (the issuer) didn't have a trustline to the asset.

Should be pretty simple to add an additional check before checking for a trustline to see if the destination is equal to the issuer address, and if so, allow the payment to proceed.

**Comment by JakeUrban** [comment]
Actually, looks like xBull actually allowed me to send the payment but indicated that it would definitely fail if I tried.

**Comment by earrietadev** [comment]
Hi @JakeUrban, it already supports burning the asset by sending it to the issuer. When the recommendation shows up if you decline the recommendation about the claimable balance, it will just send a regular payment... But this is the second time someone mentions it so maybe is bad wording on my end.

Currently the message showed in the modal is this one: https://github.com/Creit-Tech/xBull-Wallet/blob/48b548182f1f546ce64b1b224b572a73e5b25044/src/assets/i18n/en.json#L235

Do you think it could be explained in a better way? I could add something extra like "If you hit 'no' we will proceed with a regular payment"

**Comment by JakeUrban** [comment]
Hi @earrietadev, I think the ideal would be that xBull proceeds with the transaction normally without having to decline the claimable-balance approach when the destination matches the issuer address. I think the message is great when the destination doesn't match the issuer though.

**Comment by earrietadev** [comment]
@JakeUrban I just pushed the last version of xBull (v1.17.0) which also includes a check so it doesn't show the claimable balance option when sending to the issuer and proceeds to burn it directly.

The initial idea was allowing issuers to lock supply without burning by sending a claimable balance to the asset issuer. But I will move that to the "lab" section and explain better the use case there

**Comment by JakeUrban** [comment]
Cool thanks!
