### ISSUE TITLE
Clicking the "Send payment" button just loads for minutes

### ISSUE THREAD

**Issue by Bios-Marcel** [Creit-Tech/xBull-Wallet#15]
I am not sure if this is a bug or a feature, but it feels like a bug to me.

Is this normal? If so, maybe it could be indicated with a "be patentient, this can take up to X minutes" label before the button?

**Comment by earrietadev** [comment]
Hi @Bios-Marcel, is not a feature nor a bug but instead a current issue with the public Horizon Api hosted by the Stellar foundation which is the one that comes by default with the Wallet. xBull allows you to add your own Horizon Api or user a third one.

For example go to Settings > Horizon Apis and hit in "Add api" with third party horizon like the one from Public Node https://horizon.publicnode.org/

Then just select that network and you should be able to send the payment without issues

**Comment by Bios-Marcel** [comment]
Nice, thanks for the quick reply!
