### ISSUE TITLE
Allow making payments to Contracts (C addresses) 

### ISSUE THREAD

**Issue by tomerweller** [Creit-Tech/xBull-Wallet#17]
Smart wallets are starting to pick momentum in the Stellar ecosystem. 
For their adoption it's crucial that existing wallets interoperate well with them. 
An important building block for that interoperability is making payments to contracts. 
In the case of Stellar assets, it means invoking the SAC `transfer()` function instead of a classic payment, when the destination is a contract.

**Comment by earrietadev** [comment]
Version v1.31.0 of the wallet now supports this by allowing users to define an RPC to use in the settings, this version also includes a refactor in the "operations" page so it shows payments sent and received to contracts (for classic assets).

This version was just pushed to all compatible platforms, it should be public in the next few days
