### ISSUE TITLE
Cant find the xBullSDK object on localhost

### ISSUE THREAD

**Issue by MuhammadHassanAmin** [Creit-Tech/xBull-Wallet#2]
![image](https://user-images.githubusercontent.com/26143205/147670984-ea1a9829-3752-437e-9d90-c0137ee48d18.png)

**Comment by earrietadev** [comment]
Hi @MuhammadHassanAmin, this is the expected behavior because by default xBull Wallet ignores any kind of non-SSL website so if yo need to use the wallet in your development you will need to enable HTTPS in your localhost

**Comment by earrietadev** [comment]
Hi @MuhammadHassanAmin, this is the expected behavior because by default xBull Wallet ignores any kind of non-HTTPS website. If yo need to use the wallet in your development you will need to enable HTTPS in your localhost

**Comment by MuhammadHassanAmin** [comment]
Hi @earrietadev thanks for your reply, used ngrok to enable HTTPS on localhost and it worked thank you!
