### ISSUE TITLE
Typo in alert message when removing a wallet

### ISSUE THREAD

**Issue by fsodano** [Creit-Tech/xBull-Wallet#3]
👋  I was removing a wallet today and found a small typo, it should read "once it's removed" but it reads "once it's remove", without the final 'd'.

https://github.com/Creit-Tech/xBull-Wallet/blob/9d1172039cc838c755940d9db54a7ea7b0f1010b/src/app/modules/settings/pages/registered-wallet-details/registered-wallet-details.component.ts#L142

**Comment by earrietadev** [comment]
Good catch! Fixed and deployed with commit https://github.com/Creit-Tech/xBull-Wallet/commit/aec6f0b8707a1e1fbbcb7d0ff59222359f17a5b6
