### ISSUE TITLE
WalletConnect is not working

### ISSUE THREAD

**Issue by jmysliv** [Creit-Tech/xBull-Wallet#7]
While trying to connect to Dapp via WalletConnect protocol I received the error: `There was an error when talking with WalletConnect protocol`. It happens for every dapp (i.ex. https://www.stellarx.com/login, https://stellarterm.com/)
![xbull](https://user-images.githubusercontent.com/48885911/191190285-5bf56a21-fe6b-4e2d-9656-43fb262f8a2d.png)

**Comment by earrietadev** [comment]
Hi @jmysliv, can you please share the version and platform of xBull you are using (version number and platform like Chrome, Firefox, web, Android or iOS).

One thing to keep in mind is that sometimes WalletConnect servers don't work correctly for a moment. Please try again and let me know, I tried with all of my devices in those two websites you mentioned and they worked correctly.

Regards.

**Comment by earrietadev** [comment]
@jmysliv unfortunately I was not able to replicate it on my end using the chrome extension version, are you using the correct network supported by the website? (in the case of StellarX that's the public network IE not the testnet)

If you are using the correct network, can you please try with another platform and let me know if you get the same error?

**Comment by jmysliv** [comment]
@earrietadev that was it! Thanks for the help, I thought that testnet is supported as well.
