### ISSUE TITLE
(Bug) Counter asset option disappear if you change from Xlm default 

### ISSUE THREAD

**Issue by dan195794** [Creit-Tech/xBull-Wallet#8]
I get stuck with whatever i chose forever 

![IMG-20221111-WA0019.jpg](https://user-images.githubusercontent.com/63321711/201413914-970fd3a5-184b-4cd9-a015-558c84961bee.jpg)

-![IMG-20221111-WA0018.jpg](https://user-images.githubusercontent.com/63321711/201413937-d5ee6c5f-4971-4cbb-9d3f-8f4038c5b539.jpg)

**Comment by earrietadev** [comment]
Hi @dan195794, thanks for notifying it. This will get fixed and included in the next version which will be deployed during the weekend.

**Comment by earrietadev** [comment]
Fix has been included in commit https://github.com/Creit-Tech/xBull-Wallet/commit/f5f3939740659e4c43cbcb747cfcef08f9deccf0, deployment already started and it's available in Firefox and PWA version. Chrome store and play store always take a few more days before updating it.

Counter asset is calculated based on trusted assets (My assets), not the assets in the popular list.
